name: Flask - Pylint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Analyse statique avec Pylint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout du projet
        uses: actions/checkout@v4

      - name: Configuration de Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installation des dépendances
        run: |
          curl -sS https://bootstrap.pypa.io/get-pip.py | python
          python -m pip install --upgrade pip setuptools wheel
          pip install -r backend/requirements.txt
          pip install pylint

      - name: Analyse du code avec Pylint
        run: |
          pylint backend/app/
